In [64]:
import pandas as pd
import numpy as np 
import seaborn as sns


In [65]:
data = sns.load_dataset('titanic')

In [66]:
data.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [67]:
df = data[['sex','embarked','alone','pclass','survived']]

In [68]:
df.head()

sex embarked  alone  pclass  survived
0    male        S  False       3         0
1  female        C  False       1         1
2  female        S   True       3         1
3  female        S  False       1         1
4    male        S   True       3         0

In [69]:
from sklearn.preprocessing import LabelEncoder

In [78]:
encode = LabelEncoder()
df['sex'] = encode.fit_transform(df['sex'])

<ipython-input-78-19d6ee395afd>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sex'] = encode.fit_transform(df['sex'])


In [79]:
df.head()

sex  embarked  alone  pclass  survived
0    1         0  False       3         0
1    0         1  False       1         1
2    0         0   True       3         1
3    0         0  False       1         1
4    1         0   True       3         0

In [72]:
oridinal_label = {k:i for i,k in enumerate(df['embarked'].unique(),0)}

In [73]:
df['embarked'] = df['embarked'].map(oridinal_label)

<ipython-input-73-672a11508cc9>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['embarked'] = df['embarked'].map(oridinal_label)


In [74]:
df.head()

sex  embarked  alone  pclass  survived
0    male         0  False       3         0
1  female         1  False       1         1
2  female         0   True       3         1
3  female         0  False       1         1
4    male         0   True       3         0

In [80]:
df['alone']=encode.fit_transform(df['alone'])

<ipython-input-80-7ec2861b0887>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['alone']=encode.fit_transform(df['alone'])


In [81]:
df.head()

sex  embarked  alone  pclass  survived
0    1         0      0       3         0
1    0         1      0       1         1
2    0         0      1       3         1
3    0         0      0       1         1
4    1         0      1       3         0

In [87]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop('survived',axis=1),df['survived'],random_state=42,test_size=0.3)

array([1, 0])

In [89]:
from sklearn.feature_selection import chi2
## Chi2   returns 2 values 
## F-Score
## p_value
f_p_values = chi2(X_train,y_train)

In [90]:
f_p_values

(array([60.41964418, 11.363384  ,  8.35778435, 17.40807208]),
 array([7.66442567e-15, 7.49062219e-04, 3.84038546e-03, 3.01542662e-05]))

In [95]:
p_values = pd.Series(f_p_values[1])
p_values.index = X_train.columns
p_values.sort_index(ascending=True)

alone       3.840385e-03
embarked    7.490622e-04
pclass      3.015427e-05
sex         7.664426e-15
dtype: float64

### Observation
##### sex column is the most important column when compared to the output feature survived