In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('train.csv')

In [3]:
data  = pd.DataFrame(data)

In [4]:
data = data.dropna()

In [5]:
X = data.drop('label',axis=1)

In [6]:
y=data['label']

In [7]:
import tensorflow as tf

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [9]:
voc_size=5000

In [10]:
messages=X.copy()

In [11]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [12]:
messages.reset_index(inplace=True)

In [13]:
!pip install nltk

In [14]:
import nltk
import re
from nltk.corpus import stopwords

In [15]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tejas.raval@simform.dom/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [16]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [17]:
corpus


['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [18]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[1881, 878, 2141, 4364, 1398, 2016, 1895, 4089, 442, 4328],
 [3410, 3508, 3495, 4347, 191, 3285, 1900],
 [927, 292, 3257, 311],
 [3716, 995, 3351, 3021, 4949, 477],
 [3064, 191, 4148, 4841, 4837, 4263, 191, 1752, 2902, 768],
 [898,
  528,
  2561,
  1450,
  1229,
  3972,
  489,
  302,
  5,
  4935,
  3683,
  962,
  703,
  3559,
  1900],
 [3817, 283, 4799, 4930, 1313, 2302, 2270, 2733, 3891, 1294, 3858],
 [3753, 3641, 1042, 3903, 2974, 2772, 3972, 4882, 3891, 1294, 3858],
 [1875, 236, 1195, 1957, 1631, 2516, 4575, 2610, 3972, 2924],
 [341, 4022, 3853, 2459, 4643, 2564, 1923, 3924],
 [2387, 1915, 2629, 2287, 862, 2198, 2926, 3041, 3656, 98, 4968],
 [3021, 4540, 1398, 2516, 3972, 2974],
 [1771, 641, 450, 28, 4220, 1074, 2605, 2438, 615],
 [471, 4071, 813, 3380, 2723, 2444, 2763, 3891, 1294, 3858],
 [1564, 3321, 2574, 4227, 2600, 3891, 1294, 3858],
 [2486, 3064, 605, 3005, 643, 1255, 1814, 2520, 3128, 134],
 [2586, 4393, 3508],
 [155, 4142, 2383, 3167, 3972, 3465, 1428, 1900],
 [4367, 422, 

Embedding Representation

In [19]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4089  442 4328]
 [   0    0    0 ...  191 3285 1900]
 [   0    0    0 ...  292 3257  311]
 ...
 [   0    0    0 ... 3891 1294 3858]
 [   0    0    0 ... 3444 3999   88]
 [   0    0    0 ... 4823 4489 1145]]


In [20]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1881,
        878, 2141, 4364, 1398, 2016, 1895, 4089,  442, 4328], dtype=int32)

LSTM Model


In [ ]:
# embedding_vector_features=40
# model=Sequential()
# model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
# model.add(LSTM(100))
# model.add(Dense(1,activation='sigmoid'))
# model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
# print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [22]:
len(embedded_docs),y.shape

(18285, (18285,))

In [23]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [24]:

X_final.shape,y_final.shape

((18285, 20), (18285,))

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.35, random_state=44)

Model Training

In [26]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=45)

Epoch 1/10
265/265 [==============================] - 7s 18ms/step - loss: 0.2954 - accuracy: 0.8603 - val_loss: 0.1929 - val_accuracy: 0.9180
Epoch 2/10
265/265 [==============================] - 5s 18ms/step - loss: 0.1288 - accuracy: 0.9512 - val_loss: 0.2007 - val_accuracy: 0.9162
Epoch 3/10
265/265 [==============================] - 5s 19ms/step - loss: 0.0901 - accuracy: 0.9680 - val_loss: 0.2343 - val_accuracy: 0.9208
Epoch 4/10
265/265 [==============================] - 5s 19ms/step - loss: 0.0623 - accuracy: 0.9791 - val_loss: 0.2530 - val_accuracy: 0.9094
Epoch 5/10
265/265 [==============================] - 4s 17ms/step - loss: 0.0453 - accuracy: 0.9853 - val_loss: 0.3076 - val_accuracy: 0.9084
Epoch 6/10
265/265 [==============================] - 4s 16ms/step - loss: 0.0279 - accuracy: 0.9907 - val_loss: 0.3564 - val_accuracy: 0.9053
Epoch 7/10
265/265 [==============================] - 4s 15ms/step - loss: 0.0181 - accuracy: 0.9947 - val_loss: 0.3829 - val_accuracy: 0.9066

Adding Dropout

In [27]:
from tensorflow.keras.layers import Dropout # type: ignore
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

Performance Metrics And Accuracy

In [28]:

y_pred = np.argmax(model.predict(X_test), axis=-1)

200/200 [==============================] - 1s 3ms/step


In [29]:
from sklearn.metrics import confusion_matrix

In [32]:

confusion_matrix(y_pred,y_test)

array([[3599, 2801],
       [   0,    0]])

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.56234375